# Default values for piazza.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgresql:
  postgresqlUsername: piazza
  postgresqlDatabase: piazza
  metrics:
    enabled: true
    image:
      repository: wrouesnel/postgres_exporter
  resources:
    requests:
      cpu: 500Mi
      memory: 1Gi

rabbitmq:
  metrics:
    enabled: true
  rabbitmq:
    username: rabbitmq

  resources:
    requests:
      cpu: 300Mi
      memory: 512Mi
  replicas: 1

image:
  tag: "0.5.0"
  pullPolicy: Always

dashboard_provider: sidecar

imagePullSecrets:
- name: forgecreds

gql:
  port: 4000
  image: dkr.piazza.app/piazza/gql
  gcsBucket: piazzaapp-uploads
  resources: {}
  replicas: 2

rtc:
  port: 4000
  image: dkr.piazza.app/piazza/rtc
  replicas: 2
  resources: {}

www:
  dns: chat.piazzaapp.com
  port: 80
  image: dkr.piazza.app/piazza/www
  replicas: 1
  resources: {}

cron:
  image: dkr.piazza.app/piazza/cron
  resources:
    requests:
      cpu: .1
      memory: 256Mi

retentionPolicy: &retentionPolicy
  name: RETENTION_POLICY
  value: 5
notificationRetentionPolicy: &notificationRetentionPolicy
  name: RETENTION_POLICY
  value: 5
inviteRetentionPolicy: &inviteRetentionPolicy
  name: RETENTION_POLICY
  value: 5

crons:
- cronName: piazza-prune-messages
  cronModule: Prune.Messages
  crontab: "0 0 * * *"
  envVars:
  - <<: *retentionPolicy
- cronName: piazza-prune-notifications
  cronModule: Prune.Notifications
  crontab: "30 0 * * *"
  envVars:
  - <<: *notificationRetentionPolicy
- cronName: piazza-prune-invites
  cronModule: Prune.Invites
  crontab: "0 1 * * *"
  envVars:
  - <<: *inviteRetentionPolicy
- cronName: piazza-prune-interactions
  cronModule: Prune.Interactions
  crontab: "30 1 * * *"
  envVars:
  - name: RETENTION_POLICY
    value: 1

sweepStatus:
  cronName: piazza-sweep-userstatus
  cronModule: Sweep.UserStatus
  crontab: "0,15,30,45 * * * *"
  envVars: []

dbPasswordSecret: piazza-postgresql
rabbitPasswordSecret: piazza-rabbitmq

ingress:
  enabled: true
  dns: chat.piazzaapp.com
  annotations:
    networking.gke.io/managed-certificates: piazza-cert

  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
