# Default values for piazza.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgresql:
  postgresqlUsername: piazza
  postgresqlDatabase: piazza
  resources:
    requests:
      cpu: .5
      memory: 1Gi

rabbitmq:
  rabbitmq:
    username: rabbitmq

  resources:
    requests:
      cpu: .3
      memory: 512Mi
  replicas: 1

image:
  tag: "0.5.0"
  pullPolicy: Always

imagePullSecrets: []

gql:
  port: 4000
  image: gcr.io/piazza-247002/gql
  gcsBucket: piazza-testing-uploads
  resources:
    requests:
      cpu: .3
      memory: 256Mi
  replicas: 2

rtc:
  port: 4000
  image: gcr.io/piazza-247002/rtc
  replicas: 2
  resources:
    requests:
      cpu: .3
      memory: .5Gi

www:
  dns: chat.piazzaapp.com
  port: 80
  image: gcr.io/piazza-247002/www
  replicas: 1
  resources:
    requests:
      cpu: .1
      memory: 256Mi

cron:
  image: gcr.io/piazza-247002/cron
  resources:
    requests:
      cpu: .1
      memory: 256Mi

retentionPolicy: &retentionPolicy
  name: RETENTION_POLICY
  value: 5
notificationRetentionPolicy: &notificationRetentionPolicy
  name: RETENTION_POLICY
  value: 5
inviteRetentionPolicy: &inviteRetentionPolicy
  name: RETENTION_POLICY
  value: 5

crons:
- cronName: piazza-prune-messages
  cronModule: Prune.Messages
  crontab: "0 0 * * *"
  envVars:
  - <<: *retentionPolicy
- cronName: piazza-prune-notifications
  cronModule: Prune.Notifications
  crontab: "30 0 * * *"
  envVars:
  - <<: *notificationRetentionPolicy
- cronName: piazza-prune-invites
  cronModule: Prune.Invites
  crontab: "0 1 * * *"
  envVars:
  - <<: *inviteRetentionPolicy



dbPasswordSecret: piazza-postgresql
rabbitPasswordSecret: piazza-rabbitmq

ingress:
  enabled: true
  dns: chat.piazzaapp.com
  annotations:
    networking.gke.io/managed-certificates: piazza-cert

  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
