# Default values for piazza.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgresql:
  postgresqlUsername: piazza
  postgresqlDatabase: piazza
  resources:
    requests:
      cpu: 1
      memory: 2Gi

rabbitmq:
  rabbitmq:
    username: rabbitmq

  resources:
    requests:
      cpu: .3
      memory: 512Mi
  replicas: 3

external-dns:
  provider: google
  txtOwnerId: piazza
  rbac:
    create: true
    serviceAccountName: external-dns
  domainFilters:
  - piazzaapp.com
  google:
    project: piazza-247002
    serviceAccountSecret: externaldns-serviceaccount

image:
  tag: "0.5.0"
  pullPolicy: Always

imagePullSecrets: []

gql:
  port: 4000
  image: gcr.io/piazza-247002/gql
  gcsBucket: mguarino-piazza
  resources:
    requests:
      cpu: .3
      memory: 256Mi
  replicas: 2

rtc:
  port: 4000
  image: gcr.io/piazza-247002/rtc
  replicas: 2
  resources:
    requests:
      cpu: .3
      memory: .5Gi

www:
  dns: chat.piazzaapp.com
  port: 80
  image: gcr.io/piazza-247002/www
  replicas: 2
  resources:
    requests:
      cpu: .1
      memory: 256Mi

cron:
  image: gcr.io/piazza-247002/cron
  resources:
    requests:
      cpu: .1
      memory: 256Mi

retentionPolicy: &retentionPolicy
  name: RETENTION_POLICY
  value: 5
notificationRetentionPolicy: &notificationRetentionPolicy
  name: RETENTION_POLICY
  value: 5

crons:
- cronName: piazza-prune-messages
  cronModule: Prune.Messages
  crontab: "0 0 * * *"
  envVars:
  - <<: *retentionPolicy
- cronName: piazza-prune-notifications
  cronModule: Prune.Notifications
  crontab: "30 0 * * *"
  envVars:
  - <<: *notificationRetentionPolicy



dbPasswordSecret: piazza-postgresql
rabbitPasswordSecret: piazza-rabbitmq

ingress:
  enabled: true
  dns: chat.piazzaapp.com
  annotations:
    networking.gke.io/managed-certificates: piazza-cert

  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
