apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-gql
  labels:
{{ include "piazza.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.gqlReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: piazza-gql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piazza-gql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: piazza
      containers:
      - name: gql
        image: "{{ .Values.image.gqlRepository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: piazza-env
        env:
        - name: HOST
          value: {{ .Values.ingress.dns }}
        - name: DEPLOYED_AT
          value: {{ .Release.Time }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitPasswordSecret }}
              key: rabbitmq-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbPasswordSecret }}
              key: postgresql-password
        ports:
        - name: http
          containerPort: {{ .Values.gqlPort }}
          protocol: TCP
        - name: epmd
          containerPort: 4369
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          httpGet:
            path: /ping
            port: http
        resources:
          {{- toYaml .Values.gqlResources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-rtc
  labels:
{{ include "piazza.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.rtcReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: piazza-rtc
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piazza-rtc
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: piazza
      containers:
      - name: rtc
        image: "{{ .Values.image.rtcRepository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: piazza-env
        env:
        - name: HOST
          value: {{ .Values.ingress.dns }}
        - name: DEPLOYED_AT
          value: {{ .Release.Time }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitPasswordSecret }}
              key: rabbitmq-password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbPasswordSecret }}
              key: postgresql-password
        ports:
        - name: http
          containerPort: {{ .Values.rtcPort }}
          protocol: TCP
        - name: epmd
          containerPort: 4369
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          httpGet:
            path: /ping
            port: http
        resources:
          {{- toYaml .Values.rtcResources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
