{{- if .Values.ingress.enabled -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: piazza-backendconfig
spec:
  timeoutSec: 43200
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: piazza-cert
spec:
  domains:
  - {{ .Values.ingress.dns }}
---
{{- $fullName := include "piazza.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "piazza.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.dns | quote }}
    http:
      paths:
      - path: /socket
        backend:
          serviceName: piazza-rtc
          servicePort: http
      - path: /socket/websocket
        backend:
          serviceName: piazza-rtc
          servicePort: http
      - path: /gql
        backend:
          serviceName: piazza-gql
          servicePort: http
      - path: /graphiql
        backend:
          serviceName: piazza-gql
          servicePort: http
      - backend:
          serviceName: piazza-www
          servicePort: http
{{- end }}
