{{- if .Values.ingress.enabled -}}
{{- $fullName := include "piazza.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "piazza.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.dns | quote }}
    secretName: piazza-tls
  rules:
  - host: {{ .Values.ingress.dns | quote }}
    http:
      paths:
      - path: /socket.*
        backend:
          serviceName: piazza-rtc
          servicePort: http
      - path: /gql
        backend:
          serviceName: piazza-gql
          servicePort: http
      - path: /external/.*
        backend:
          serviceName: piazza-gql
          servicePort: http
      - path: /graphiql
        backend:
          serviceName: piazza-gql
          servicePort: http
      - backend:
          serviceName: piazza-www
          servicePort: http
{{- end }}
