{{- if .Values.ingress.enabled -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: piazza-backendconfig
spec:
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
---
{{- $fullName := include "piazza.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "piazza.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.piazzaDns | quote }}
    http:
      paths:
      - path: /socket
        backend:
          serviceName: piazza-rtc
          servicePort: http
      - backend:
          serviceName: piazza-gql
          servicePort: http
{{- end }}
