apiVersion: batch/v1
kind: Job
metadata:
  name: piazza-migration
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: "{{ .Values.image.gqlRepository }}:{{ .Values.image.tag }}"
        command: ["/opt/app/bin/gql",  "migrate"]
        envFrom:
        - secretRef:
            name: piazza-env
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RABBITMQ_PASSWORD
          value: rabbitmq
        - name: POSTGRES_PASSWORD
          value: piazza
        # - name: RABBITMQ_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.rabbitPasswordSecret }}
        #       key: rabbitmq-password
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Values.dbPasswordSecret }}
        #       key: postgresql-password
      restartPolicy: Never
  backoffLimit: 5