apiVersion: forgelabs.sh/v1alpha1
kind: Proxy
metadata:
  name: db
  labels:
{{ include "piazza.labels" . | indent 4 }}
spec:
  type: db
  target: statefulset/piazza-postgresql
  credentials:
    secret: piazza-postgresql
    key: postgresql-password
    user: piazza
  dbConfig:
    name: piazza
    engine: postgres
    port: 5432
---
apiVersion: forgelabs.sh/v1alpha1
kind: Proxy
metadata:
  name: sh
  labels:
{{ include "piazza.labels" . | indent 4 }}
spec:
  type: sh
  target: deployment/piazza-gql
  shConfig:
    command: /opt/app/bin/gql
    args: [remote_console]
---
apiVersion: forgelabs.sh/v1alpha1
kind: Proxy
metadata:
  name: rtc
  labels:
{{ include "piazza.labels" . | indent 4 }}
spec:
  type: sh
  target: deployment/piazza-rtc
  shConfig:
    command: /opt/app/bin/rtc
    args: [remote_console]