apiVersion: v1
kind: Secret
metadata:
  name: piazza-env
  labels:
{{ include "piazza.labels" . | indent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  ERLANG_COOKIE: {{ randAlphaNum 20 | b64enc | quote }}