apiVersion: v1
kind: Secret
metadata:
  name: piazza-env
  labels:
{{ include "piazza.labels" . | indent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwt | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  ERLANG_COOKIE: {{ .Values.secrets.erlang | b64enc | quote }}
  GIPHY_SECRET: {{ .Values.secrets.giphy | b64enc | quote }}
  INVITE_SECRET: {{ .Values.secrets.invite_secret | b64enc | quote }}
  GCS_BUCKET: {{ .Values.gql.bucket }}
{{ if .Values.secrets.github_secret }}
  GITHUB_SECRET: {{ .Values.secrets.github_secret | b64enc | quote }}
  GITHUB_INCOMING_WEBHOOK: {{ .Values.secrets.github_incoming_webhook | b64enc | quote }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: piazza-migration-env
  labels:
{{ include "piazza.labels" . | indent 4 }}
type: Opaque
data:
  ADMIN_EMAIL: {{ .Values.admin.email | b64enc | quote }}
  ADMIN_NAME: {{ .Values.admin.name | b64enc | quote }}
  ADMIN_HANDLE: {{ .Values.admin.handle | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  GCS_BUCKET: {{ .Values.gql.bucket }}